### ISSUE TITLE
Cleanup Diagnostic for near-term use

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#1]
- [x] Add units to override time field
- [x] Remove eV spectrogram (for now)
- [x] Add enum display of BYKIK rate
- [x] Remove dialog boxes from override activate, deactivate, and fault ack/reset buttons

**Comment by hhslepicka** [comment]
Where would you like the BYKIK rate to be displayed? Near the `Beam Permitted | Limited` status?

**Comment by slacAWallace** [comment]
Yes, or in lieu of.

**Comment by hhslepicka** [comment]
Here is what I've got so far accomplishing the 4 items:
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/8185425/86661974-1fa88880-bfa1-11ea-81eb-b121735521f0.png">

Is this what you expected?

For Item 1... the PVs are lacking the EGU... could you please confirm that you are passing them at the PRAGMA?
```
(dev) slepicka@lfe-console pmps-ui-dev (cleanup) $ caget PMPS:LFE:FFO:01:FF:001:Ovrd:Duration
PMPS:LFE:FFO:01:FF:001:Ovrd:Duration 0
(dev) slepicka@lfe-console pmps-ui-dev (cleanup) $ caget PMPS:LFE:FFO:01:FF:001:Ovrd:Duration.EGU
PMPS:LFE:FFO:01:FF:001:Ovrd:Duration.EGU
```
