### ISSUE TITLE
ev Range Alignment

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#20]
Small nitpick:
![image](https://user-images.githubusercontent.com/24234960/92686469-94c07300-f2ee-11ea-8be1-dd756e9873e7.png)

This might be slightly more intuitive to read if the eV range values are left-justified (or is it top-justified?).

**Comment by cristinasewell** [comment]
is this what we mean here:

![rotate_label](https://user-images.githubusercontent.com/62306310/112540203-21082400-8d6f-11eb-8e00-d588e61dd34b.PNG)

Or do we simply want to just move the text a bit closer to the bits?:

![closer_labels](https://user-images.githubusercontent.com/62306310/112540483-7a705300-8d6f-11eb-9ef5-6f2136cf820b.PNG)
