### ISSUE TITLE
Rendering on 13" laptop is tough

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#25]
Rendering using MobaXterm, Windows 10, 13" laptop, 3200x1800.

PMPS display can only show a few words in fast faults, and some of the filter mechanisms are obscured.

![image](https://user-images.githubusercontent.com/24234960/100553806-fab0fc80-3244-11eb-9691-18574cd58dd4.png)

**Comment by ZLLentz** [comment]
Here's what it looks like on my laptop screen right now, resolution 1366x768:

![image](https://user-images.githubusercontent.com/10647860/119045650-960f6880-b970-11eb-8840-fcc50fd0671d.png)


Can I close this issue, Alex? Or do I need to support even smaller resolutions?

Is there some desire to make these rows thinner again?
