### ISSUE TITLE
Warning for No In-Use FFOs, Disconnected IOC

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pmps-ui#26]
- If a PLC boots and has all FFOs as not in-use, this should be represented somewhere in the diagnostic
- If an IOC is down, this should be represented somewhere in the diagnostic

**Comment by ZLLentz** [comment]
Not high priority I think, but I want to record this for later thoughts/plans/updates

**Comment by slacAWallace** [comment]
@cristinasewell This is a good one as well.

**Comment by cristinasewell** [comment]
> * If a PLC boots and has all FFOs as not in-use, this should be represented somewhere in the diagnostic
> * If an IOC is down, this should be represented somewhere in the diagnostic

@ZLLentz did you have anything in mind of how you think these two scenarios should be represented?

**Comment by ZLLentz** [comment]
I'm not sure how you'd go about incorporating it into the big lists of FFO, etc., so it might be best to represent in a new PLC/IOC status tab.

One idea of implementation/how to represent:
We could provide the config file a mapping of the plc name to the IOC heartbeat PV (an integer counter PV that goes up as the IOC stays online), and then the GUI could display rows of plc name + active FFO count + heartbeat + connected/disconnected state. 

I'm not sure what the best filtering options would be here.

**Comment by cristinasewell** [comment]
Thanks Zach!!
Do we have these particular IOCs in a place somewhere?

**Comment by ZLLentz** [comment]
There's a huge conglomeration of all the ioc data at `/cds/group/iocData`
Tomorrow I can track down specific examples that we would want to track in the UI

**Comment by cristinasewell** [comment]
That's great - thanks a lot!

**Comment by ZLLentz** [comment]
Some examples, the ones I found are much more well structured then I expected, perhaps no additional information in the config file is needed?
```
plc name - plc prefix (already used in config file) - heartbeat pv
plc-lfe-motion - PLC:LFE:MOTION - PLC:LFE:MOTION:HEARTBEAT
plc-kfe-motion - PLC:KFE:MOTION - PLC:KFE:MOTION:HEARTBEAT
plc-tmo-motion - PLC:TMO:MOTION - PLC:TMO:MOTION:HEARTBEAT
plc-kfe-rix-motion - PLC:KFE:RIX:MOTION - PLC:KFE:RIX:MOTION:HEARTBEAT
```
So we can e.g. ignore the plc name, use the plc prefix as an identifier, and add a heartbeat pv connection.
Sample portion of LFE config file for reference:
```
  - prefix: "PLC:LFE:MOTION:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50
```

**Comment by cristinasewell** [comment]
I can't find what IOC we're using for this guy: `PLC:TMO:VAC:`  - but this works - so i'll assume is this one:
```
caget PLC:TMO:VAC:HEARTBEAT.DESC` works
PLC:TMO:VAC:HEARTBEAT.DESC     1 Hz counter since startup
```

Also not sure if I found the correct info for these two:
- `PLC:KFE:GATT:`  - looking into this ioc `ioc-plc-kfe-gatt`  - I don't think it has a correct pv for the prefix, so maybe I am looking in the wrong place (`PREFIX:HEARTBEAT` - this is what is has) - 

it also seems like it has up to 75 ffs? per ffo (in pvs) - are we just not using all of them? (i need to investigate the code more though, i think i might be missing something)
```
PLC:KFE:GATT:FFO:01:FF:001:Info:InUse_RBV, "bi" 
to 
PLC:KFE:GATT:FFO:02:FF:075:Info:InUse_RBV, "bi"
```
- ` PLC:KFE:VAC:K0:` - has up to 10 ffs per ffo (and 4 ffo) (in pvs) - but the heartbeat pv works

```
PLC:KFE:VAC:K0:FFO:01:FF:001:Info:InUse_RBV, "bi"
to
PLC:KFE:VAC:K0:FFO:04:FF:010:Info:InUse_RBV, "bi"

```

**Comment by ZLLentz** [comment]
> `PREFIX:HEARTBEAT`

That would be an error in the IOC setup... someone forgot to swap from the default prefix of `PREFIX`, oops! I suspect we'll find all such instances of this with this improved diagnostic tool. I'll look for the appropriate repo to post an issue on.

> it also seems like it has up to 75 ffs? per ffo (in pvs) - are we just not using all of them?

Because of how the PLCs are set up, it's easiest to allocate extra fast faults even if we don't use them all. We use the `InUse_RBV` to note if that particular index is in use.

**Comment by cristinasewell** [comment]
Ok great, thank you Zach 👍

**Comment by cristinasewell** [comment]
Just to make sure because I've been looking through PVs and can't find something that would give me the info for the `active FFO count` - do I get this info based on how many we create in the Fast Faults widget per PLC - is this the count we're looking for?

Also, I want to double check this:

"_GUI could display rows of plc name + active FFO count + heartbeat + connected/disconnected state._"

Something like this sketch below? or did I over simplified it?
![plc_ioc_status](https://user-images.githubusercontent.com/62306310/110068587-dd4f6b00-7d2a-11eb-9bb3-d296bbc664f2.PNG)

Also, for the `connected/disconnected` - is that when we're not able to read PVs at all, or is it when the heartbeat is not increasing/changing in a certain time period? I guess I want to understand (because I am not sure yet how it works) if there is a difference between when an IOC is disconnected, and when a PLC boots? Can we have a PLC boot and IOC being connected?

**Comment by ZLLentz** [comment]
Your sketch looks good to me, no reason to overcomplicate it.

Let's define "active ffo count" as the number of fast fault widgets we create for the prefix (same number as the number of PVs in the group with InUse_RBV == True). There is an issue if this number ends up as zero (e.g. all of our fast faults are broken, something is not safe)

For connected/disconnected, I was thinking about the state where we are unable to read the PVs at all. Heartbeat not increasing is a separate diagnostic that you can see in the same line, no need to combine it into the connection status. The reason I want this included is because if all the PVs in one of these IOCs is disconnected, it gets filtered out in the Fast Fault tab and you don't see any indication that anything is missing.

Some quick background: the PLC and the IOC are separate items running on different hardware. The PLC does all the real time logic with respect to defining when there is a fault and making sure the beam is kicked. The IOC is our interface that reads/writes information from/to the PLC. "Booting" is when a PLC turns on. It's possible for the IOC to be down, the PLC to be down, both to be down, or both to be up.

Thinking about this more, we probably need one more item to catch the case where the IOC is up but the PLC is down...

**Comment by ZLLentz** [comment]
I think the best we have right now is using the `.SEVR` field of a representative PV. If the PV is connected but the `.SEVR` field is invalid, it means the PLC is down but the IOC is up (I think?)

**Comment by cristinasewell** [comment]
Ohh got it - thank you, the key here is that if IOCs are disconnected the pvs get filtered out - and we don't  have an indication for that - good to know

I'll look into `.SEVR` field, not familiar with it yet - thank you :)
