### ISSUE TITLE
Move Grafana Log Into a Tab

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#27]

**Comment by cristinasewell** [comment]
After moving the `Grafana Log` into a tab, do we want to adjust the `Requested Beam Parameters` a bit differently - maybe separate them into two parts, making `eV` a separated frame? 

Something like this sketch below: 
![top-screen](https://user-images.githubusercontent.com/62306310/109728538-3ec8db80-7b6b-11eb-8b59-b885159dfbba.png)

Or should they stay as is for now?

**Comment by slacAWallace** [comment]
That was exactly the subject of the next issue I was writing. Yes, the overall goal is to expand the vertical space for the fast faults and preemptive tabs below.
