### ISSUE TITLE
Stop Button for Beam

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#3]
Need to add a button to Play/Pause the beam. It enter a requested rate of 0Hz and hit apply to the Line Beam Parameters Control element and be accessible outside the tab views (so always available).

**Comment by hhslepicka** [comment]
Is it supposed to be an `Emergency Stop` kind of thing?
By `Play/Pause` it makes me believe that someone will want to hit play and get the config back up again... is that the case?

**Comment by ZLLentz** [comment]
@slacAWallace is this still needed?

**Comment by ZLLentz** [comment]
Implemented a while back from a Jira ticket description, closing
