### ISSUE TITLE
Add bit selection for photon energy bitmask control

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#32]
Under the line parameters control tab, Photon Energy Ranges needs to be adjustable by selecting bits, in a manner similar to how it's displayed in the Beam Parameter Status panel.

![image](https://user-images.githubusercontent.com/24234960/110081207-70df6680-7d40-11eb-84d0-a9c16987d139.png)

![image](https://user-images.githubusercontent.com/24234960/110081253-82287300-7d40-11eb-8514-24280ed662dc.png)

**Comment by cristinasewell** [comment]
Is the idea here that one can check one of those 16 bits and when clicked on the `Apply` button the range associated with that bit will be sent to the the correct PV?
 
Or can the user select one of those bits (I am assuming we can use PyDMEnumButtons here) and the energy would be sent directly, without the `Apply` button being pressed?

Do we usually send a specific number, somewhere in the middle of the range, or how does that work?

Or am I getting this wrong completely :)?

**Comment by cristinasewell** [comment]
So this `Apply` button is pretty cool, it is actually an `.Apply`  PV ?

I might still not understand how it all of it, but how do we want to go about setting the bits?
 - we can select the bits we want, and when we're ready we can click the `<<` button to `"set"` it (set the text to the EditLine where the pv is at?)]
 -  we can directly set the EditLine as soon as we change a bit - and not have a `set` button at all, but this will write to the pv more often... if i understand correctly
 
This is what kind of what I mean:
![energy_range_calc](https://user-images.githubusercontent.com/62306310/110863452-8fc88600-8275-11eb-8bcc-3a2819ae324d.PNG)

**Comment by slacAWallace** [comment]
Looks like the right direction. The units "eV" should be dropped, as should the number. The second option is best. Multiple writes are perfectly OK.

The apply button is a boolean in the PLC (and integrated into EPICS as an :Apply PV) that PyDM writes a 1 to. On a rising edge the function block latches the request and pushes it to the controls interfaces. Then it writes a false back to the boolean (sort of like a physical, springloaded pushbutton).

**Comment by slacAWallace** [comment]
O and if you weren't already going to do this, have the range indicator beneath the bitmask so people know what each bitmask bit means please!

**Comment by cristinasewell** [comment]
Ok, those are the evRangeConstants correct?
