### ISSUE TITLE
Need ability to sort preemptive requests

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#34]
Would be really helpful to be able to sort or filter the preemptive request list like the fast fault list.

![image](https://user-images.githubusercontent.com/24234960/110088915-527e6880-7d4a-11eb-9189-ec7fc44a5e7d.png)

**Comment by cristinasewell** [comment]
Do we want to be able to Filter based on: 
 - Rate
 - Transmission
 - Pulse Energy
 - cohort Number

Anything else?

**Comment by slacAWallace** [comment]
I am not sure filtering is exactly what we'd want, although it does get us partially there since a user could easily put something less than full rate and see all the stuff they likely care about.

Cohort can be omitted.

For bitmask, essentially anything that does have all the bits lit is going to be interesting. Bitmask actually would work well with filtering.

**Comment by cristinasewell** [comment]
> I am not sure filtering is exactly what we'd want, although it does get us partially there since a user could easily put something less than full rate and see all the stuff they likely care about.

Probably **sorting** is a better option here for `rate` and `transmission`? Sorting from lowest-highest and vice versa - or some other type of sorting?

**Comment by slacAWallace** [comment]
Yep, low to high will be most helpful. The most common use of this tab is checking where a zero rate request is coming from. Likewise with the transmission.

**Comment by ZLLentz** [comment]
closed by #49
